apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: metallb-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      version: "0.14.9"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1h
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab
  namespace: metallb-system
spec:
  addresses:
    - 192.168.9.200-192.168.9.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab
  namespace: metallb-system
spec:
  ipAddressPools:
    - homelab
